# Generated by Django 5.2 on 2025-09-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("college", models.CharField(max_length=100, verbose_name="学院")),
            ],
        ),
    ]
