# Generated by Django 5.2 on 2025-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='source_type',
            field=models.CharField(choices=[('course_outline', '课程大纲'), ('announcement', '课程公告'), ('assignment_answer', '作业标准答案'), ('faq', '常见问题'), ('course_file', '课程文件')], help_text='文档来源类型', max_length=20),
        ),
    ]