# Generated by Django 5.2 on 2025-09-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_knowledge_document_course_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteraction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='courses.course'),
        ),
    ]