# Generated by Django 5.2 on 2025-09-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="评语"),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="分数",
            ),
        ),
    ]
